### ISSUE TITLE
Crash using up arrow to recall commands

### ISSUE THREAD

**Issue by ExcitedName** [Mrbysco/SpellChecker#1]
## Client Info
* Minecraft Version: 1.12.2

* Forge Version: 14.23.2.2643
* Mod Version: 1.02
* Java Version: 1.8.0_144

## Issue Description 
I think the title of my issue says enough. I'm not usually rude on here, but I have to say this was the most annoying bug report I have ever made. And I report them often. I almost didn't even take the time to do this. It would be much easier and less time consuming to just remove a mod that has such little content. All of the information you are so strictly requiring, other than the description of the issue, can be found in the crash report. Why not just be strict with getting the crash report? And lets really think about it, you are asking people to go out of their way to give you information that can easily be obtained from the report to help YOU fix your mod. And if someone doesn't adhere to your bug reporting standards you won't fix your own mod?. Just doesn't make sense to me. A good title, a brief description and a pastebin link with my crash report, boom done in two minutes. 

## Additional Information
https://pastebin.com/1wrNZeks

**Comment by Mrbysco** [comment]
Thank you for reporting. Will fix it soon

**Comment by Mrbysco** [comment]
I believe I've found the cause. If you can test out the next release.

**Comment by Mrbysco** [comment]
https://minecraft.curseforge.com/projects/spell-checker/files/2643826
