### ISSUE TITLE
1.20 update [Suggestion]: 

### ISSUE THREAD

**Issue by Ultimushadow** [Mrbysco/SpellChecker#3]
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

Hey there, I could not find any information regarding a plan to update to 1.20, so I wanted to ask to double check. Please let me know what your thoughts on an update are, thanks!

**Comment by Mrbysco** [comment]
Done in https://github.com/Mrbysco/SpellChecker/commit/d8ab01f0f54dac95cc0a94e276520ac40c791d11

**Comment by Ultimushadow** [comment]
Thanks for the update!
